import { useCallback, useEffect, useState } from 'react';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5001/api';
const money = new Intl.NumberFormat('ar-SA', { style: 'currency', currency: 'SAR', maximumFractionDigits: 0 });
const allowedImageTypes = ['image/jpeg', 'image/png', 'image/webp'];
const validateImageFile = (file) => !file ? 'اختر صورة أولًا.' : !allowedImageTypes.includes(file.type) ? 'الصيغ المسموحة: JPEG أو PNG أو WebP.' : file.size > 5 * 1024 * 1024 ? 'حجم الصورة يجب ألا يتجاوز 5MB.' : '';
const nav = [['dashboard','▦','الرئيسية'],['bookings','◫','الحجوزات'],['customers','♙','العملاء'],['decorations','✦','الديكورات'],['services','◌','الخدمات'],['payments','◈','المدفوعات والفواتير']];
const emptyBooking = {customerId:'',decorationId:'',eventType:'حفل زفاف',eventDate:'',startTime:'18:00',endTime:'22:00',eventLocation:'',depositAmount:0,bookingStatus:'Draft'};

export default function App() {
  const [token,setToken]=useState(()=>localStorage.getItem('booking_token'));
  const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('booking_user')||'null'));
  const [page,setPage]=useState('dashboard'),[modal,setModal]=useState(null),[notice,setNotice]=useState(null),[loading,setLoading]=useState(false);
  const [data,setData]=useState({summary:{},customers:[],decorations:[],services:[],bookings:[],payments:[],invoices:[]});
  const logout=()=>{localStorage.removeItem('booking_token');localStorage.removeItem('booking_user');setToken(null);setUser(null)};
  const flash=(message,type='success')=>{setNotice({message,type});setTimeout(()=>setNotice(null),3500)};
  const api=useCallback(async(path,options={})=>{const r=await fetch(`${API_URL}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`} : {}),...options.headers}});const result=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401)logout();throw new Error(result.message||'تعذر إتمام الطلب.')}return result},[token]);
  const load=useCallback(async()=>{if(!token)return;setLoading(true);try{const [summary,customers,decorations,services,bookings,payments,invoices]=await Promise.all([api('/dashboard/summary'),api('/customers'),api('/decorations'),api('/services'),api('/bookings'),api('/payments'),api('/invoices')]);setData({summary,customers:customers.customers||[],decorations:decorations.decorations||[],services:services.services||[],bookings:bookings.bookings||[],payments:payments.payments||[],invoices:invoices.invoices||[]})}catch(e){flash(e.message,'error')}finally{setLoading(false)}},[token,api]);
  useEffect(()=>{load()},[load]);
  const create=async(path,payload,message)=>{try{await api(path,{method:'POST',body:JSON.stringify(payload)});setModal(null);await load();flash(message)}catch(e){flash(e.message,'error')}};
  const uploadImage=async(id,file,{silent=false}={})=>{const validationError=validateImageFile(file);if(validationError){if(!silent)flash(validationError,'error');return false}try{const body=new FormData();body.append('image',file);const response=await fetch(`${API_URL}/decorations/${id}/image`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body});const result=await response.json();if(!response.ok)throw new Error(result.message||'تعذر رفع الصورة');await load();if(!silent)flash('تم رفع صورة الديكور بنجاح');return true}catch(e){if(!silent)flash(e.message,'error');return false}};
  const createDecoration=async(payload,file)=>{try{const created=await api('/decorations',{method:'POST',body:JSON.stringify(payload)});setModal(null);if(file){const uploaded=await uploadImage(created.decoration.id,file,{silent:true});if(!uploaded){await load();flash('تم إنشاء الديكور، لكن رفع الصورة فشل. يمكنك إضافتها لاحقًا.','error');return}}await load();flash(file?'تم إنشاء الديكور ورفع صورته بنجاح':'تمت إضافة الديكور بنجاح')}catch(e){flash(e.message,'error')}};
  const title=nav.find(x=>x[0]===page)?.[2];
  if(!token)return <Login onLogin={(r)=>{localStorage.setItem('booking_token',r.token);localStorage.setItem('booking_user',JSON.stringify(r.user));setToken(r.token);setUser(r.user)}}/>;
  const quick=page==='customers'?'عميل':page==='decorations'?'ديكور':page==='services'?'خدمة':page==='payments'?'دفعة':'حجز'; const canManageImages=['Super Admin','Manager'].includes(user?.role);
  return <div className="dashboard-shell" dir="rtl"><aside className="sidebar"><div className="brand"><span>B</span><div><strong>بُكرة</strong><small>إدارة المناسبات</small></div></div><nav>{nav.map(([id,icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><i>{icon}</i>{label}</button>)}</nav><div className="side-user"><span>{user?.fullName?.[0]||'م'}</span><div><b>{user?.fullName||user?.username}</b><small>{user?.role}</small></div></div><button className="logout" onClick={logout}>تسجيل الخروج ←</button></aside><main className="main"><header><div><p>إدارة أعمالك بسهولة</p><h1>{title}</h1></div><div className="actions"><button className="refresh" onClick={load}>↻</button><button className="primary" onClick={()=>setModal(page==='customers'?'customer':page==='decorations'?'decoration':page==='services'?'service':page==='payments'?'payment':'booking')}>＋ إضافة {quick}</button></div></header>{notice&&<div className={`notice ${notice.type}`}>{notice.type==='error'?'!':'✓'} {notice.message}</div>}{loading&&<div className="loading"/>}{page==='dashboard'&&<Dashboard data={data} go={setPage}/>} {page==='bookings'&&<Bookings {...data} confirm={async id=>{try{await api(`/bookings/${id}/confirm`,{method:'PATCH'});load();flash('تم تأكيد الحجز')}catch(e){flash(e.message,'error')}}}/>} {page==='customers'&&<Customers customers={data.customers}/>} {page==='decorations'&&<Decorations decorations={data.decorations} uploadImage={uploadImage} canManageImages={canManageImages}/>} {page==='services'&&<Services services={data.services}/>} {page==='payments'&&<Payments {...data} invoice={b=>create('/invoices',{bookingId:b.id},'تم إنشاء الفاتورة')}/>}</main>{modal==='customer'&&<CustomerModal close={()=>setModal(null)} save={x=>create('/customers',x,'تمت إضافة العميل')}/>} {modal==='decoration'&&<DecorationModal close={()=>setModal(null)} save={createDecoration}/>} {modal==='service'&&<ServiceModal close={()=>setModal(null)} save={x=>create('/services',x,'تمت إضافة الخدمة')}/>} {modal==='booking'&&<BookingModal {...data} close={()=>setModal(null)} save={x=>create('/bookings',x,'تم إنشاء الحجز')}/>} {modal==='payment'&&<PaymentModal bookings={data.bookings} close={()=>setModal(null)} save={x=>create('/payments',x,'تم تسجيل الدفعة')}/>}</div>;
}

function Login({onLogin}){const [f,set]=useState({username:'admin',password:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`${API_URL}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)}),x=await r.json();if(!r.ok)throw new Error(x.message||'تعذر تسجيل الدخول');onLogin(x)}catch(e){setError(e.message)}finally{setBusy(false)}};return <div className="login" dir="rtl"><section className="login-art"><div className="logo">B</div><p>منصة بُكرة</p><h1>كل مناسبة جميلة<br/>تبدأ بتنظيم رائع.</h1><span>من مكان واحد، أدر الحجوزات والعملاء والدفعات بكل وضوح وأناقة.</span></section><section className="login-form"><form onSubmit={submit}><div className="mobile-logo">B</div><h2>مرحبًا بعودتك</h2><p>سجّل دخولك للوصول إلى لوحة التحكم.</p>{error&&<div className="error">{error}</div>}<Field label="اسم المستخدم"><input autoFocus value={f.username} onChange={e=>set({...f,username:e.target.value})}/></Field><Field label="كلمة المرور"><input required type="password" value={f.password} onChange={e=>set({...f,password:e.target.value})}/></Field><button className="primary full" disabled={busy}>{busy?'جارٍ الدخول...':'تسجيل الدخول ←'}</button><small>استخدم بيانات المسؤول المحددة في ملف البيئة للمشروع.</small></form></section></div>}
function Dashboard({data,go}){const s=data.summary||{}, recent=data.bookings.slice(0,5);return <><section className="welcome"><div><span>✦ نظرة اليوم</span><h2>أهلًا بك، جاهز ليوم مليء بالإنجاز؟</h2><p>تابع عملياتك المالية وحجوزاتك القادمة من مكان واحد.</p></div><b>✦</b></section><section className="stats"><Stat title="إجمالي الحجوزات" value={s.totalBookings||0} icon="◫" c="purple"/><Stat title="حجوزات مؤكدة" value={s.confirmed||0} icon="✓" c="green"/><Stat title="إجمالي الإيرادات" value={money.format(s.totalRevenue||0)} icon="◈" c="orange"/><Stat title="المبالغ المتبقية" value={money.format(s.totalRemaining||0)} icon="◌" c="rose"/></section><section className="dash-grid"><div className="panel"><Panel title="أحدث الحجوزات" action="عرض الكل" click={()=>go('bookings')}/>{recent.length?<div className="recent">{recent.map(b=><div key={b.id}><span className="date">{String(b.event_date||'').slice(-2)}<small>{String(b.event_date||'').slice(5,7)}</small></span><p><b>{b.event_type}</b><small>{b.event_location}</small></p><Status v={b.booking_status}/><strong>{money.format(b.total_amount||0)}</strong></div>)}</div>:<Empty text="لا توجد حجوزات حتى الآن"/>}</div><div className="panel finance"><Panel title="ملخص التحصيل"/><div className="circle"><div><b>{s.totalRevenue?Math.round(s.totalPaid/s.totalRevenue*100):0}%</b><small>تم تحصيله</small></div></div><p><i/> المحصل <b>{money.format(s.totalPaid||0)}</b></p><p><i className="pale"/> المتبقي <b>{money.format(s.totalRemaining||0)}</b></p></div></section></>}
const Stat=({title,value,icon,c})=><article className="stat"><span className={c}>{icon}</span><div><small>{title}</small><h3>{value}</h3></div></article>;const Panel=({title,action,click})=><div className="panel-title"><h3>{title}</h3>{action&&<button onClick={click}>{action} ←</button>}</div>;const Empty=({text})=><div className="empty">⌁<br/>{text}</div>;const Status=({v})=><span className={`status ${String(v||'').toLowerCase().replaceAll(' ','-')}`}>{({Confirmed:'مؤكد',Draft:'مسودة',Cancelled:'ملغي',Available:'متاح',Active:'نشط','Fully Paid':'مكتمل','Partially Paid':'جزئي',Unpaid:'غير مدفوع'})[v]||v}</span>;
function Bookings({bookings,customers,decorations,confirm}){const cs=Object.fromEntries(customers.map(x=>[x.id,x.full_name])),ds=Object.fromEntries(decorations.map(x=>[x.id,x.name]));return <section className="panel table-panel"><Panel title="سجل الحجوزات"/><div className="scroll"><table><thead><tr><th>العميل</th><th>المناسبة</th><th>الديكور</th><th>التاريخ والوقت</th><th>الحالة</th><th>الإجمالي</th><th/></tr></thead><tbody>{bookings.map(b=><tr key={b.id}><td><b>{cs[b.customer_id]||'عميل'}</b><small>{b.event_location}</small></td><td>{b.event_type}</td><td>{ds[b.decoration_id]||'—'}</td><td>{b.event_date}<small>{b.start_time} — {b.end_time}</small></td><td><Status v={b.booking_status}/></td><td><b>{money.format(b.total_amount||0)}</b><small>متبقي: {money.format(b.remaining_amount||0)}</small></td><td>{b.booking_status==='Draft'&&<button className="link" onClick={()=>confirm(b.id)}>تأكيد</button>}</td></tr>)}</tbody></table>{!bookings.length&&<Empty text="أضف أول حجز لتبدأ التنظيم"/>}</div></section>}
function Customers({customers}){return <section className="panel customers"><Panel title={`${customers.length} عميل مسجل`}/><div>{customers.map(c=><article key={c.id}><span>{c.full_name?.[0]}</span><p><b>{c.full_name}</b><small>{c.phone}</small></p><em>{c.address||'لا يوجد عنوان مسجل'}</em></article>)}</div>{!customers.length&&<Empty text="لا يوجد عملاء مسجلون"/>}</section>}
function Decorations({decorations,uploadImage,canManageImages}){return <section className="catalog">{decorations.map((d,i)=><article key={d.id}><div className={`art a${i%4}`}>{d.image_url?<img src={`http://localhost:5001${d.image_url}`} alt={d.name}/>:<b>✦</b>}<Status v={d.status}/>{canManageImages&&<label className="card-image-action">{d.image_url?'تغيير الصورة':'إضافة صورة'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&uploadImage(d.id,e.target.files[0])}/></label>}</div><div><small>{d.category}</small><h3>{d.name}</h3><p>{d.description||'ديكور مميز لمناسبتك الخاصة.'}</p><b>{money.format(d.base_price||d.price||0)}</b></div></article>)}{!decorations.length&&<Empty text="أضف ديكوراتك لعرضها هنا"/>}</section>}
function Services({services}){return <section className="services">{services.map(s=><article key={s.id}><span>✧</span><div><h3>{s.name}</h3><p>{s.description||'خدمة إضافية للمناسبة'}</p><b>{money.format(s.price||0)}</b></div><Status v={s.status}/></article>)}{!services.length&&<Empty text="أضف خدماتك الإضافية هنا"/>}</section>}
function Payments({payments,invoices,bookings,invoice}){return <div className="pay-grid"><section className="panel table-panel"><Panel title="آخر الدفعات"/><div className="scroll"><table><thead><tr><th>الطريقة</th><th>المبلغ</th><th>التاريخ</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>{p.payment_method}</td><td><b>{money.format(p.amount)}</b></td><td>{p.payment_date?.slice(0,10)||'—'}</td></tr>)}</tbody></table>{!payments.length&&<Empty text="لا توجد دفعات مسجلة"/>}</div></section><section className="panel invoices"><Panel title="الفواتير"/>{invoices.map(i=><div className="invoice" key={i.id}><span>▤</span><p><b>{i.invoice_number}</b><small>{i.customer_name}</small></p><strong>{money.format(i.total||0)}</strong></div>)}{bookings.filter(b=>!invoices.some(i=>i.booking_id===b.id)).slice(0,3).map(b=><button key={b.id} onClick={()=>invoice(b)}>＋ إنشاء فاتورة لـ {b.event_type}</button>)}</section></div>}
function Modal({title,close,children,submit,label='حفظ البيانات'}){return <div className="backdrop" onMouseDown={close}><form className="modal" onMouseDown={e=>e.stopPropagation()} onSubmit={submit}><header><h2>{title}</h2><button type="button" onClick={close}>×</button></header><main>{children}</main><footer><button type="button" className="secondary" onClick={close}>إلغاء</button><button className="primary">{label} ←</button></footer></form></div>};const Field=({label,children})=><label className="field"><span>{label}</span>{children}</label>;
function CustomerModal({close,save}){const [f,set]=useState({fullName:'',phone:'',alternativePhone:'',address:'',notes:''});return <Modal title="إضافة عميل جديد" close={close} submit={e=>{e.preventDefault();save(f)}}><div className="form-grid"><Field label="الاسم الكامل"><input required value={f.fullName} onChange={e=>set({...f,fullName:e.target.value})}/></Field><Field label="رقم الجوال"><input required value={f.phone} onChange={e=>set({...f,phone:e.target.value})}/></Field><Field label="رقم بديل"><input value={f.alternativePhone} onChange={e=>set({...f,alternativePhone:e.target.value})}/></Field><Field label="العنوان"><input value={f.address} onChange={e=>set({...f,address:e.target.value})}/></Field></div><Field label="ملاحظات"><textarea value={f.notes} onChange={e=>set({...f,notes:e.target.value})}/></Field></Modal>}
function DecorationModal({close,save}){const [f,set]=useState({name:'',description:'',category:'Wedding',basePrice:'',status:'Available'}),[image,setImage]=useState(null),[preview,setPreview]=useState(''),[error,setError]=useState(''),[inputKey,setInputKey]=useState(0);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);const choose=e=>{const file=e.target.files?.[0];const message=validateImageFile(file);setError(message);if(message)return;setImage(file);setPreview(URL.createObjectURL(file))};const remove=()=>{setImage(null);setError('');setPreview('');setInputKey(x=>x+1)};return <Modal title="إضافة ديكور" close={close} submit={e=>{e.preventDefault();save(f,image)}}><div className="form-grid"><Field label="اسم الديكور"><input required value={f.name} onChange={e=>set({...f,name:e.target.value})}/></Field><Field label="التصنيف"><select value={f.category} onChange={e=>set({...f,category:e.target.value})}>{['Wedding','Engagement','Birthday','Graduation','Corporate','Other'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="السعر الأساسي"><input type="number" min="0" value={f.basePrice} onChange={e=>set({...f,basePrice:e.target.value})}/></Field><Field label="الحالة"><select value={f.status} onChange={e=>set({...f,status:e.target.value})}><option>Available</option><option>Maintenance</option><option>Inactive</option></select></Field></div><Field label="الوصف"><textarea value={f.description} onChange={e=>set({...f,description:e.target.value})}/></Field><section className="decoration-image-field"><span>صورة الديكور</span><div className="image-picker">{preview?<img src={preview} alt="معاينة صورة الديكور"/>:<div><b>▧</b><p>أضف صورة لتظهر في معرض الديكورات</p></div>}<label className="primary image-choice">اختيار صورة<input key={inputKey} type="file" accept="image/jpeg,image/png,image/webp" onChange={choose}/></label></div>{image&&<div className="selected-image"><span>{image.name} <small>({(image.size/1024/1024).toFixed(2)} MB)</small></span><button type="button" onClick={remove}>إزالة الصورة</button></div>}{error&&<div className="image-error">{error}</div>}<small>JPEG أو PNG أو WebP — الحد الأقصى 5MB</small></section></Modal>}
function ServiceModal({close,save}){const [f,set]=useState({name:'',description:'',price:''});return <Modal title="إضافة خدمة" close={close} submit={e=>{e.preventDefault();save(f)}}><div className="form-grid"><Field label="اسم الخدمة"><input required value={f.name} onChange={e=>set({...f,name:e.target.value})}/></Field><Field label="السعر"><input type="number" min="0" value={f.price} onChange={e=>set({...f,price:e.target.value})}/></Field></div><Field label="وصف الخدمة"><textarea value={f.description} onChange={e=>set({...f,description:e.target.value})}/></Field></Modal>}
function BookingModal({customers,decorations,services,close,save}){const[f,set]=useState(emptyBooking),[chosen,setChosen]=useState([]);const toggle=s=>setChosen(chosen.some(x=>x.id===s.id)?chosen.filter(x=>x.id!==s.id):[...chosen,{id:s.id,quantity:1,unitPrice:s.price}]);return <Modal title="حجز مناسبة جديدة" label="إنشاء الحجز" close={close} submit={e=>{e.preventDefault();save({...f,services:chosen})}}><div className="form-grid"><Field label="العميل"><select required value={f.customerId} onChange={e=>set({...f,customerId:e.target.value})}><option value="">اختر العميل</option>{customers.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></Field><Field label="الديكور"><select required value={f.decorationId} onChange={e=>set({...f,decorationId:e.target.value})}><option value="">اختر الديكور</option>{decorations.map(d=><option key={d.id} value={d.id}>{d.name} — {money.format(d.base_price||0)}</option>)}</select></Field><Field label="نوع المناسبة"><input required value={f.eventType} onChange={e=>set({...f,eventType:e.target.value})}/></Field><Field label="الموقع"><input required value={f.eventLocation} onChange={e=>set({...f,eventLocation:e.target.value})}/></Field><Field label="التاريخ"><input required type="date" value={f.eventDate} onChange={e=>set({...f,eventDate:e.target.value})}/></Field><Field label="من الساعة"><input required type="time" value={f.startTime} onChange={e=>set({...f,startTime:e.target.value})}/></Field><Field label="إلى الساعة"><input required type="time" value={f.endTime} onChange={e=>set({...f,endTime:e.target.value})}/></Field><Field label="العربون"><input type="number" min="0" value={f.depositAmount} onChange={e=>set({...f,depositAmount:e.target.value})}/></Field></div>{services.length>0&&<div className="picker"><span>خدمات إضافية</span>{services.map(s=><button type="button" className={chosen.some(x=>x.id===s.id)?'chosen':''} onClick={()=>toggle(s)} key={s.id}>{chosen.some(x=>x.id===s.id)?'✓ ':''}{s.name} <b>{money.format(s.price||0)}</b></button>)}</div>}</Modal>}
function PaymentModal({bookings,close,save}){const[f,set]=useState({bookingId:'',amount:'',paymentMethod:'Cash',referenceNumber:''});return <Modal title="تسجيل دفعة" close={close} submit={e=>{e.preventDefault();save(f)}}><Field label="الحجز"><select required value={f.bookingId} onChange={e=>set({...f,bookingId:e.target.value})}><option value="">اختر الحجز</option>{bookings.filter(b=>Number(b.remaining_amount)>0).map(b=><option key={b.id} value={b.id}>{b.event_type} — متبقي {money.format(b.remaining_amount)}</option>)}</select></Field><div className="form-grid"><Field label="مبلغ الدفعة"><input required type="number" min="1" value={f.amount} onChange={e=>set({...f,amount:e.target.value})}/></Field><Field label="طريقة الدفع"><select value={f.paymentMethod} onChange={e=>set({...f,paymentMethod:e.target.value})}><option>Cash</option><option>Bank Transfer</option><option>Card</option></select></Field></div><Field label="رقم المرجع (اختياري)"><input value={f.referenceNumber} onChange={e=>set({...f,referenceNumber:e.target.value})}/></Field></Modal>}
