import { useEffect, useState } from 'react';

const STORAGE_KEY = 'booking-system-auth';
const menu = [
  ['dashboard', 'لوحة التحكم', '⌂'], ['bookings', 'الحجوزات', '▣'], ['decorations', 'الكوشات', '◆'], ['services', 'الخدمات الإضافية', '＋'],
  ['customers', 'العملاء', '♙'], ['employees', 'الموظفون', '♧'], ['installations', 'التجهيز والتركيب', '⚒'], ['payments', 'المدفوعات', '◇'],
  ['invoices', 'الفواتير', '▤'], ['reports', 'التقارير', '▥'], ['calendar', 'التقويم', '▦'], ['notifications', 'الإشعارات', '◌'], ['users', 'المستخدمون', '♚'], ['settings', 'الإعدادات', '⚙'], ['audit', 'سجل التدقيق', '◈'],
];
const statusLabels = { Draft: 'مسودة', 'Pending Confirmation': 'بانتظار التأكيد', Confirmed: 'مؤكد', Preparing: 'قيد التجهيز', 'Assigned for Installation': 'تم تعيين فريق التركيب', 'Installation in Progress': 'جاري التركيب', Installed: 'تم التركيب', Completed: 'مكتمل', Cancelled: 'ملغي', Available: 'متاحة', Reserved: 'محجوزة', Maintenance: 'تحت الصيانة', Inactive: 'غير متاحة', Unpaid: 'غير مدفوع', 'Partially Paid': 'مدفوع جزئياً', 'Fully Paid': 'مدفوع بالكامل', Active: 'نشط' };
const roleLabels = { 'Super Admin': 'مدير النظام', Manager: 'مدير', Accountant: 'محاسب', 'Booking Employee': 'موظف حجوزات', 'Installation Employee': 'موظف تركيب' };
const rolePermissions = { 'Super Admin': ['*'], Manager: ['users:', 'customers:', 'decorations:', 'services:', 'bookings:', 'payments:', 'invoices:', 'employees:', 'installations:', 'reports:', 'notifications:', 'audit:'], 'Booking Employee': ['customers:', 'decorations:', 'services:', 'bookings:', 'payments:', 'invoices:', 'installations:', 'notifications:'], 'Installation Employee': ['decorations:', 'bookings:', 'installations:', 'notifications:'], Accountant: ['customers:', 'bookings:', 'payments:', 'invoices:', 'reports:', 'notifications:'] };
const api = async (endpoint, options = {}, token) => { const isFormData = options.body instanceof FormData; const response = await fetch(endpoint, { ...options, headers: { ...(isFormData ? {} : { 'Content-Type': 'application/json' }), ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } }); const text = await response.text(); const payload = text ? JSON.parse(text) : {}; if (!response.ok) throw new Error(payload.message || 'تعذر تنفيذ الطلب'); return payload; };
const money = (value) => `${Number(value || 0).toFixed(2)} ر.س`;
const label = (value) => statusLabels[value] || value || 'غير محدد';
function Status({ value }) { return <span className={`status status-${String(value || '').toLowerCase().replaceAll(' ', '-')}`}>{label(value)}</span>; }
function Empty({ text = 'لا توجد بيانات لعرضها حالياً' }) { return <div className="empty"><strong>لا توجد نتائج</strong><span>{text}</span></div>; }
function Field({ label: title, ...props }) { return <label className="field"><span>{title}</span><input {...props} /></label>; }
function SelectField({ label: title, children, ...props }) { return <label className="field"><span>{title}</span><select {...props}>{children}</select></label>; }
function DecorationCard({ item, onBook, onDetails }) { return <article className="decoration-card"><div className="decoration-image">{item.image || item.image_url ? <img src={item.image || item.image_url} alt={item.name} /> : <div className="image-placeholder"><span>✦</span><small>صورة الكوشة</small></div>}</div><div className="decoration-body"><div className="card-heading"><h3>{item.name}</h3><Status value={item.status} /></div><p>{item.description || 'تصميم أنيق لمناسبتك الخاصة'}</p><strong className="price">{money(item.base_price)}</strong><div className="card-actions"><button className="button secondary" onClick={() => onDetails(item)}>عرض التفاصيل</button><button className="button primary" onClick={() => onBook(item)} disabled={item.status !== 'Available'}>حجز الكوشة</button></div></div></article>; }

function App() {
  const [auth, setAuth] = useState(() => { const saved = localStorage.getItem(STORAGE_KEY); return saved ? JSON.parse(saved) : null; });
  const [activePage, setActivePage] = useState('dashboard'); const [selectedDecoration, setSelectedDecoration] = useState(null); const [loginData, setLoginData] = useState({ username: 'admin', password: 'change-me-now' }); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const [dashboard, setDashboard] = useState({}); const [customers, setCustomers] = useState([]); const [decorations, setDecorations] = useState([]); const [services, setServices] = useState([]); const [bookings, setBookings] = useState([]); const [employees, setEmployees] = useState([]); const [installations, setInstallations] = useState([]); const [payments, setPayments] = useState([]); const [invoices, setInvoices] = useState([]); const [notifications, setNotifications] = useState([]); const [auditLogs, setAuditLogs] = useState([]); const [users, setUsers] = useState([]); const [reports, setReports] = useState({});
  const token = auth?.token || ''; const permissions = auth?.user?.permissions || rolePermissions[auth?.user?.role] || [];
  useEffect(() => { auth ? localStorage.setItem(STORAGE_KEY, JSON.stringify(auth)) : localStorage.removeItem(STORAGE_KEY); }, [auth]);
  const canSee = (key) => permissions.includes('*') || !['users', 'audit', 'employees', 'installations', 'payments', 'invoices', 'reports'].includes(key) || permissions.some((p) => p.startsWith(`${key}:`));
  const refreshAll = async () => { if (!auth) return; try { const result = await Promise.all([api('/api/dashboard/summary', {}, token), api('/api/customers', {}, token), api('/api/decorations', {}, token), api('/api/services', {}, token), api('/api/bookings', {}, token), api('/api/employees', {}, token), api('/api/installations', {}, token), api('/api/payments', {}, token), api('/api/invoices', {}, token), api('/api/notifications', {}, token), api('/api/audit-logs', {}, token), api('/api/users', {}, token), api('/api/reports/summary', {}, token)]); const [d, c, de, s, b, e, i, p, inv, n, a, u, r] = result; setDashboard(d || {}); setCustomers(c.customers || []); setDecorations(de.decorations || []); setServices(s.services || []); setBookings(b.bookings || []); setEmployees(e.employees || []); setInstallations(i.assignments || []); setPayments(p.payments || []); setInvoices(inv.invoices || []); setNotifications(n.notifications || []); setAuditLogs(a.logs || []); setUsers(u.users || []); setReports(r || {}); setError(''); } catch (err) { setError(err.message); } };
  useEffect(() => { if (auth) refreshAll(); }, [auth, token]);
  const submit = async (event, endpoint, transform, success = () => {}) => { event.preventDefault(); try { await api(endpoint, { method: 'POST', body: JSON.stringify(transform(new FormData(event.currentTarget))) }, token); event.currentTarget.reset(); await refreshAll(); success(); } catch (err) { setError(err.message); } };
  const handleLogin = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { setAuth(await api('/api/auth/login', { method: 'POST', body: JSON.stringify(loginData) })); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  const createCustomer = (e) => submit(e, '/api/customers', (f) => ({ fullName: f.get('fullName'), phone: f.get('phone'), alternativePhone: f.get('alternativePhone'), address: f.get('address'), notes: f.get('notes') }));
  const createDecoration = (e) => submit(e, '/api/decorations', (f) => ({ name: f.get('name'), description: f.get('description'), category: f.get('category') || 'Wedding', basePrice: Number(f.get('basePrice') || 0), status: f.get('status') || 'Available', availability: f.get('availability') === 'on', notes: f.get('notes') }));
  const createService = (e) => submit(e, '/api/services', (f) => ({ name: f.get('name'), description: f.get('description'), price: Number(f.get('price') || 0), quantity: Number(f.get('quantity') || 1), status: f.get('status') || 'Active' }));
  const createEmployee = (e) => submit(e, '/api/employees', (f) => ({ fullName: f.get('fullName'), phone: f.get('phone'), employeeType: f.get('employeeType') || 'Installation', gender: f.get('gender'), status: 'Active' }));
  const createPayment = (e) => submit(e, '/api/payments', (f) => ({ bookingId: f.get('bookingId'), amount: Number(f.get('amount') || 0), paymentMethod: f.get('paymentMethod') || 'Cash', referenceNumber: f.get('referenceNumber'), notes: f.get('notes') }));
  const createNotification = (e) => submit(e, '/api/notifications', (f) => ({ title: f.get('title'), message: f.get('message'), type: 'info' }));
  const createUser = (e) => submit(e, '/api/users', (f) => ({ username: f.get('username'), fullName: f.get('fullName'), password: f.get('password'), role: f.get('role') || 'Manager', isActive: true }));
  const createInstallation = (e) => submit(e, '/api/installations', (f) => ({ bookingId: f.get('bookingId'), employeeId: f.get('employeeId'), assignedDate: f.get('assignedDate'), installationDate: f.get('installationDate'), installationTime: f.get('installationTime'), status: 'Assigned', notes: f.get('notes') }));
  const bookingSubmit = (e) => submit(e, '/api/bookings', (f) => { const chosen = services.filter((s) => f.getAll('services').includes(s.id)).map((s) => ({ serviceId: s.id, unitPrice: Number(s.price || 0), quantity: 1 })); return { customerId: f.get('customerId'), decorationId: f.get('decorationId'), eventType: f.get('eventType') || 'Wedding', eventDate: f.get('eventDate'), startTime: f.get('startTime'), endTime: f.get('endTime'), eventLocation: f.get('eventLocation'), locationDetails: f.get('locationDetails'), notes: f.get('notes'), discount: Number(f.get('discount') || 0), depositAmount: Number(f.get('depositAmount') || 0), services: chosen, bookingStatus: 'Draft' }; }, () => { setSelectedDecoration(null); setActivePage('bookings'); });
  if (!auth) return <div className="auth-page"><form className="auth-card" onSubmit={handleLogin}><div className="brand-mark">✦</div><p className="eyebrow">نظام إدارة المناسبات</p><h1>مرحباً بك</h1><p className="muted">سجّل الدخول لإدارة الحجوزات والتجهيزات</p>{error && <div className="alert error">{error}</div>}<Field label="اسم المستخدم" value={loginData.username} onChange={(e) => setLoginData({ ...loginData, username: e.target.value })} required /><Field label="كلمة المرور" type="password" value={loginData.password} onChange={(e) => setLoginData({ ...loginData, password: e.target.value })} required /><button className="button primary full" type="submit" disabled={loading}>{loading ? 'جارٍ الدخول...' : 'تسجيل الدخول'}</button></form></div>;
  const openBooking = (item) => { setSelectedDecoration(item); setActivePage('booking-form'); };
  const table = (headers, rows) => <div className="table-wrap"><table><thead><tr>{headers.map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length ? rows : <tr><td colSpan={headers.length}><Empty /></td></tr>}</tbody></table></div>;
  const resources = { customers: ['العملاء', createCustomer, ['الاسم', 'الهاتف', 'العنوان', 'ملاحظات'], customers.map((c) => <tr key={c.id}><td>{c.full_name}</td><td dir="ltr">{c.phone}</td><td>{c.address || '—'}</td><td>{c.notes || '—'}</td></tr>)], services: ['الخدمات الإضافية', createService, ['الخدمة', 'السعر', 'الكمية', 'الحالة'], services.map((s) => <tr key={s.id}><td>{s.name}</td><td>{money(s.price)}</td><td>{s.quantity}</td><td><Status value={s.status} /></td></tr>)], employees: ['الموظفون', createEmployee, ['الاسم', 'الهاتف', 'النوع', 'الحالة'], employees.map((e) => <tr key={e.id}><td>{e.full_name}</td><td>{e.phone}</td><td>{e.employee_type}</td><td><Status value={e.status} /></td></tr>)], installations: ['التجهيز والتركيب', createInstallation, ['الحجز', 'الموظف', 'التاريخ', 'الحالة'], installations.map((i) => <tr key={i.id}><td>{i.booking_id}</td><td>{i.employee_id}</td><td>{i.installation_date || i.assigned_date}</td><td><Status value={i.status} /></td></tr>)], payments: ['المدفوعات', createPayment, ['الحجز', 'المبلغ', 'الطريقة', 'التاريخ'], payments.map((p) => <tr key={p.id}><td>{p.booking_id}</td><td>{money(p.amount)}</td><td>{p.payment_method}</td><td>{p.payment_date}</td></tr>)], invoices: ['الفواتير', null, ['رقم الفاتورة', 'الحجز', 'الإجمالي', 'المدفوع', 'المتبقي', 'الحالة'], invoices.map((i) => <tr key={i.id}><td>{i.invoice_number}</td><td>{i.booking_id}</td><td>{money(i.total)}</td><td>{money(i.paid)}</td><td>{money(i.remaining)}</td><td><Status value={i.payment_status} /></td></tr>)], notifications: ['الإشعارات', createNotification, ['العنوان', 'الرسالة', 'النوع'], notifications.map((n) => <tr key={n.id}><td>{n.title}</td><td>{n.message}</td><td>{n.type}</td></tr>)], users: ['المستخدمون', createUser, ['اسم المستخدم', 'الاسم', 'الدور', 'الحالة'], users.map((u) => <tr key={u.id}><td>{u.username}</td><td>{u.full_name}</td><td>{roleLabels[u.role] || u.role}</td><td>{u.is_active ? 'نشط' : 'غير نشط'}</td></tr>)] };
  const renderPage = () => {
    if (activePage === 'dashboard') return <><div className="page-intro"><div><p className="eyebrow">نظرة عامة</p><h1>لوحة التحكم</h1><p>تابع الحجوزات والمدفوعات وتجهيز المناسبات من مكان واحد.</p></div><button className="button primary" onClick={() => setActivePage('bookings')}>＋ حجز جديد</button></div><div className="stats">{[['إجمالي الحجوزات', dashboard.totalBookings], ['حجوزات اليوم', dashboard.todayBookings], ['الحجوزات القادمة', dashboard.confirmed], ['إجمالي الإيرادات', money(dashboard.totalRevenue)], ['إجمالي المدفوع', money(dashboard.totalPaid)], ['المبالغ المتبقية', money(dashboard.totalRemaining)], ['دفعات معلقة', dashboard.pendingPayments], ['الكوشات المتاحة', decorations.filter((d) => d.status === 'Available').length]].map(([t, v]) => <div className="stat-card" key={t}><span>{t}</span><strong>{v || 0}</strong></div>)}</div><section className="panel"><h2>ملخص حالات الحجوزات</h2>{table(['الحالة', 'العدد'], Object.entries(dashboard.bookingStatusSummary || {}).map(([s, c]) => <tr key={s}><td><Status value={s} /></td><td>{c}</td></tr>))}</section></>;
    if (activePage === 'bookings' || activePage === 'decorations') return <Gallery title={activePage === 'bookings' ? 'الحجوزات' : 'معرض الكوشات'} subtitle="اختر التصميم المناسب لمناسبتك ثم ابدأ الحجز مباشرة." items={decorations} onBook={openBooking} onDetails={() => {}} extra={activePage === 'decorations' && <DecorationForm token={token} onSaved={refreshAll} onError={setError} />} />;
    if (activePage === 'booking-form') return <BookingForm decoration={selectedDecoration} customers={customers} services={services} onSubmit={bookingSubmit} onBack={() => setActivePage('bookings')} />;
    if (resources[activePage]) { const [title, handler, headers, rows] = resources[activePage]; return <Resource title={title} form={handler && <ResourceForm title={title} handler={handler} />} content={table(headers, rows)} />; }
    if (activePage === 'reports') return <><div className="page-intro"><div><p className="eyebrow">الأداء المالي والتشغيلي</p><h1>التقارير</h1></div></div><div className="stats">{[['إجمالي الحجوزات', reports.totalBookings], ['الإيرادات', money(reports.totalRevenue)], ['المدفوعات', money(reports.totalPaid)], ['المبالغ المستحقة', money(reports.totalRemaining)]].map(([t, v]) => <div className="stat-card" key={t}><span>{t}</span><strong>{v || 0}</strong></div>)}</div></>;
    if (activePage === 'calendar') return <Resource title="التقويم" content={table(['التاريخ', 'النوع', 'المناسبة', 'الحالة'], bookings.map((b) => <tr key={b.id}><td>{b.event_date}</td><td>حجز</td><td>{b.event_type}</td><td><Status value={b.booking_status} /></td></tr>))} />;
    if (activePage === 'audit') return <Resource title="سجل التدقيق" content={table(['المستخدم', 'الإجراء', 'العنصر', 'التاريخ'], auditLogs.map((l) => <tr key={l.id}><td>{l.user_id}</td><td>{l.action}</td><td>{l.entity}</td><td>{l.created_at}</td></tr>))} />;
    if (activePage === 'users') return <Resource title="المستخدمون" content={table(['اسم المستخدم', 'الاسم', 'الدور', 'الحالة'], users.map((u) => <tr key={u.id}><td>{u.username}</td><td>{u.full_name}</td><td>{roleLabels[u.role] || u.role}</td><td>{u.is_active ? 'نشط' : 'غير نشط'}</td></tr>))} />;
    return <Resource title="الإعدادات" content={table(['الإعداد', 'القيمة'], [<tr key="backend"><td>الخادم وقاعدة البيانات</td><td>Express + PostgreSQL</td></tr>, <tr key="auth"><td>المصادقة والصلاحيات</td><td>JWT + RBAC</td></tr>])} />;
  };
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span><div>مراسم<small>إدارة المناسبات</small></div></div><nav>{menu.filter(([key]) => canSee(key)).map(([key, text, icon]) => <button key={key} className={activePage === key ? 'nav active' : 'nav'} onClick={() => { setActivePage(key); setSelectedDecoration(null); }}><span>{icon}</span>{text}</button>)}</nav><button className="logout" onClick={() => setAuth(null)}>تسجيل الخروج <span>↪</span></button></aside><main className="main-panel"><header className="topbar"><div><small>مرحباً بعودتك</small><h2>{auth.user.fullName || auth.user.username}</h2></div><span className="role-badge">{roleLabels[auth.user.role] || auth.user.role}</span></header>{error && <div className="alert error">{error}<button onClick={() => setError('')}>×</button></div>}<div className="page-content">{renderPage()}</div></main></div>;
}
function Gallery({ title, subtitle, items, onBook, onDetails, extra }) { return <section><div className="page-intro"><div><p className="eyebrow">اختيار التصميم</p><h1>{title}</h1><p>{subtitle}</p></div><span className="count-badge">{items.length} تصميم</span></div>{extra && <div className="panel form-panel"><h2>إضافة كوشة جديدة</h2>{extra}</div>}<div className="gallery">{items.length ? items.map((item) => <DecorationCard key={item.id} item={item} onBook={onBook} onDetails={onDetails} />) : <Empty text="ستظهر الكوشات المضافة من قاعدة البيانات هنا" />}</div></section>; }
function DecorationForm({ token, onSaved, onError }) {
  const [file, setFile] = useState(null); const [preview, setPreview] = useState(''); const [saving, setSaving] = useState(false);
  const chooseFile = (event) => { const selected = event.target.files?.[0]; if (!selected) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(selected.type)) { onError('نوع الصورة غير مسموح. استخدم JPG أو JPEG أو PNG أو WebP.'); event.target.value = ''; return; } if (selected.size > 5 * 1024 * 1024) { onError('حجم الصورة يجب ألا يتجاوز 5 ميجابايت.'); event.target.value = ''; return; } setFile(selected); setPreview(URL.createObjectURL(selected)); onError(''); };
  const clearFile = () => { if (preview) URL.revokeObjectURL(preview); setFile(null); setPreview(''); };
  const submit = async (event) => { event.preventDefault(); const formElement = event.currentTarget; setSaving(true); onError(''); try { const form = new FormData(formElement); const created = await api('/api/decorations', { method: 'POST', body: JSON.stringify({ name: form.get('name'), description: form.get('description'), category: form.get('category') || 'Wedding', basePrice: Number(form.get('basePrice') || 0), status: form.get('status') || 'Available', availability: true }) }, token); if (file) { const imageData = new FormData(); imageData.append('image', file); await api(`/api/decorations/${created.decoration.id}/image`, { method: 'POST', body: imageData }, token); } formElement.reset(); clearFile(); await onSaved(); } catch (error) { onError(error.message); } finally { setSaving(false); } };
  return <form className="decoration-form" onSubmit={submit}><div className="form-grid"><Field label="اسم الكوشة" name="name" required /><Field label="الوصف" name="description" /><Field label="السعر الأساسي" name="basePrice" type="number" min="0" defaultValue="0" /><SelectField label="الحالة" name="status"><option value="Available">متاحة</option><option value="Reserved">محجوزة</option><option value="Maintenance">تحت الصيانة</option><option value="Inactive">غير متاحة</option></SelectField></div><label className="upload-zone"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseFile} disabled={saving} /><span className="upload-icon">⇧</span><strong>اختر صورة الكوشة</strong><small>JPG أو PNG أو WebP، بحد أقصى 5 ميجابايت</small></label>{file && <div className="upload-preview"><img src={preview} alt="معاينة الكوشة" /><div><strong>{file.name}</strong><small>{(file.size / 1024 / 1024).toFixed(2)} ميجابايت</small></div><button type="button" className="text-button" onClick={clearFile}>إزالة</button></div>}<button className="button primary" type="submit" disabled={saving}>{saving ? 'جارٍ حفظ الكوشة...' : 'حفظ الكوشة'}</button></form>; }
function ResourceForm({ title, handler }) { if (title === 'العملاء') return <form className="inline-form" onSubmit={handler}><Field label="اسم العميل" name="fullName" required /><Field label="رقم الهاتف" name="phone" required /><Field label="العنوان" name="address" /><button className="button primary">إضافة عميل</button></form>; if (title === 'الخدمات الإضافية') return <form className="inline-form" onSubmit={handler}><Field label="اسم الخدمة" name="name" required /><Field label="الوصف" name="description" /><Field label="السعر" name="price" type="number" defaultValue="0" /><button className="button primary">إضافة خدمة</button></form>; if (title === 'الموظفون') return <form className="inline-form" onSubmit={handler}><Field label="اسم الموظف" name="fullName" required /><Field label="رقم الهاتف" name="phone" /><Field label="نوع العمل" name="employeeType" defaultValue="Installation" /><button className="button primary">إضافة موظف</button></form>; if (title === 'التجهيز والتركيب') return <form className="inline-form" onSubmit={handler}><Field label="معرّف الحجز" name="bookingId" required /><Field label="معرّف الموظف" name="employeeId" required /><Field label="تاريخ التركيب" name="installationDate" type="date" /><button className="button primary">تعيين الفريق</button></form>; if (title === 'المدفوعات') return <form className="inline-form" onSubmit={handler}><Field label="معرّف الحجز" name="bookingId" required /><Field label="المبلغ" name="amount" type="number" required /><Field label="طريقة الدفع" name="paymentMethod" defaultValue="Cash" /><button className="button primary">تسجيل دفعة</button></form>; if (title === 'المستخدمون') return <form className="inline-form" onSubmit={handler}><Field label="اسم المستخدم" name="username" required /><Field label="الاسم الكامل" name="fullName" required /><Field label="كلمة المرور" name="password" type="password" required /><Field label="الدور" name="role" defaultValue="Manager" /><button className="button primary">إنشاء مستخدم</button></form>; return <form className="inline-form" onSubmit={handler}><Field label="عنوان الإشعار" name="title" required /><Field label="نص الإشعار" name="message" required /><button className="button primary">إرسال إشعار</button></form>; }
function Resource({ title, form, content }) { return <section className="resource"><div className="page-intro"><div><p className="eyebrow">إدارة النظام</p><h1>{title}</h1></div></div>{form && <div className="panel form-panel">{form}</div>}<div className="panel">{content}</div></section>; }
function BookingForm({ decoration, customers, services, onSubmit, onBack }) { const [selected, setSelected] = useState([]); const [discount, setDiscount] = useState(0); const base = Number(decoration?.base_price || 0); const addOns = services.filter((s) => selected.includes(s.id)).reduce((sum, s) => sum + Number(s.price || 0), 0); const total = Math.max(base + addOns - Number(discount || 0), 0); return <section className="booking-flow"><button className="back-button" onClick={onBack}>→ العودة إلى المعرض</button><div className="page-intro"><div><p className="eyebrow">الخطوة الأخيرة</p><h1>حجز الكوشة: {decoration?.name || 'غير محددة'}</h1><p>أدخل تفاصيل المناسبة، ثم راجع ملخص السعر قبل التأكيد.</p></div></div><div className="selected-decoration"><div className="mini-image">✦</div><div><span>الكوشة المختارة</span><h2>{decoration?.name}</h2></div><strong>{money(base)}</strong></div><form onSubmit={onSubmit}><div className="booking-layout"><div><div className="panel form-panel"><h2>بيانات العميل والمناسبة</h2><div className="form-grid"><SelectField label="العميل" name="customerId" required><option value="">اختر العميل</option>{customers.map((c) => <option key={c.id} value={c.id}>{c.full_name} - {c.phone}</option>)}</SelectField><SelectField label="نوع المناسبة" name="eventType"><option value="Wedding">زفاف</option><option value="Engagement">خطوبة</option><option value="Other">مناسبة أخرى</option></SelectField><Field label="تاريخ المناسبة" name="eventDate" type="date" required /><Field label="وقت البداية" name="startTime" type="time" required /><Field label="وقت النهاية" name="endTime" type="time" required /><Field label="موقع المناسبة" name="eventLocation" required /><Field label="تفاصيل الموقع" name="locationDetails" /><Field label="ملاحظات" name="notes" /></div></div><div className="panel form-panel"><h2>الخدمات الإضافية</h2><div className="service-options">{services.filter((s) => s.status === 'Active').map((s) => <label className="service-option" key={s.id}><input type="checkbox" name="services" value={s.id} onChange={(e) => setSelected(e.target.checked ? [...selected, s.id] : selected.filter((id) => id !== s.id))} /><span>{s.name}</span><strong>{money(s.price)}</strong></label>)}</div></div></div><aside className="summary"><h2>ملخص الحجز</h2><div><span>السعر الأساسي</span><strong>{money(base)}</strong></div><div><span>الخدمات الإضافية</span><strong>{money(addOns)}</strong></div><label className="field"><span>الخصم</span><input name="discount" type="number" min="0" value={discount} onChange={(e) => setDiscount(e.target.value)} /></label><div className="summary-total"><span>الإجمالي النهائي</span><strong>{money(total)}</strong></div><label className="field"><span>المبلغ المدفوع</span><input name="depositAmount" type="number" min="0" defaultValue="0" /></label><button className="button primary full" type="submit">تأكيد الحجز</button></aside></div><input type="hidden" name="decorationId" value={decoration?.id || ''} /></form></section>; }
export default App;
